name: Despertar Streamlit

on:
  schedule:
    - cron: '0 0 * * *' # Esto se ejecuta todos los días a las 00:00 UTC
  workflow_dispatch:      # Esto te permite probarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Visitar la App
        run: |
          curl -I https://braker.streamlit.app/
